#pragma once
enum EToken {
    TEOF, TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE,
    TEQUAL, TNOTEQU, TLESSE, TGREATE, TAND, TOR, TINC, TDEC,
    TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN,
    TPLUS, TMINUS, TASSIGN, TNOT, TLESS, TGREATER, TMULT,
    TLPAREN, TRPAREN, TCOMMA, TLBRACE, TRBRACE, TLBRACKET, TRBRACKET, TSEMICOLON,
    TIDENT, TNUMBER, TOCTAL, THEX, TFLOAT, TCHAR, TSTRING, TERROR
};
